version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: khalid
      POSTGRES_PASSWORD: datascientest
      POSTGRES_DB: dst_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: khalid.kherrazi@gmail.com
      PGADMIN_DEFAULT_PASSWORD: data_engineer
    ports:
      - "5050:80"